---
# Download https://raw.fgit.cf/Leyoud/LEYOUD/master/Clash/user_config.yaml
#
#-------------------------------------------------------------#
# Clashä½¿ç”¨æ‰‹å†Œ https://dreamacro.github.io/clash/zh_CN/
# Clashç®¡ç†é¢æ¿ https://clash.razord.top https://yacd.haishan.me
#-------------------------------------------------------------#
# cfw General
mixed-port: 7890
external-ui: ./
log-level: info
allow-lan: false
bind-address: '*'
external-controller: 127.0.0.1:9090 # or 0.0.0.0:9090
secret: ''
ipv6: false
#-------------------------------------------------------------#
# cfw Profiles
mode: rule
authentication: []

# é…ç½®è¯´æ˜:
# 1. defaults.subURL åŸºäº https://github.com/tindy2013/subconverter
# 2. rule-providers  åŸºäº https://github.com/ACL4SSR/ACL4SSR https://github.com/blackmatrix7/ios_rule_script

defaults:
  {
    # æ·»åŠ æœåŠ¡å•†æä¾›è®¢é˜…(url=...) sub.xeton.dev(subconverteräº‘ç«¯) or 127.0.0.1:25500(subconverteræœ¬åœ°)
    subURL: &subURL 'http://sub.xeton.dev/sub?target=clash&new_name=true&url=|è®¢é˜…é“¾æ¥1|è®¢é˜…é“¾æ¥2|è®¢é˜…é“¾æ¥++|https%3A%2F%2Fraw.githubusercontent.com%2FLeyoud%2FLEYOUD%2Fmaster%2FClash%2Fproxies_Debug.yaml&emoji=true&list=true&udp=true',

    # è®¢é˜…å’Œè§„åˆ™æ›´æ–°æ—¶é—´(s)
    providersHTTPInterval: &providersHTTPInterval 86400, # 24h

    # å»¶è¿Ÿæµ‹è¯•åœ°å€ & é—´éš”æ—¶é•¿(s)
    delayInterval: &delayInterval { url: https://www.gstatic.com/generate_204, interval: 300 },

    # url-test å»¶è¿Ÿå®¹å·®(ms)
    urlTestTolerance: &urlTestTolerance 150
  }

dns:
  {
    enable: true, listen: 0.0.0.0:53, ipv6: true, use-hosts: true,

    enhanced-mode: fake-ip, fake-ip-range: 198.18.0.1/16, fake-ip-filter: ['*.msftncsi.com', '*.msftconnecttest.com'],

    nameserver: [tls://dns.alidns.com:853, https://dns.alidns.com/dns-query], # default-nameserver: [223.6.6.6, 223.5.5.5],

    fallback: [208.67.222.222, 208.67.220.220, https://doh.opendns.com/dns-query], fallback-filter: { geoip: true, geoip-code: CN }
  }

hosts: { localhost: 127.0.0.1, ip6-localhost: '::1'}

tun: { enable: true, stack: gvisor, auto-route: true, auto-detect-interface: true, dns-hijack: [any:53] }

proxyProviders: &proxyProviders { url: *subURL, type: http, interval: *providersHTTPInterval, health-check: { enable: true, <<: *delayInterval } }

proxyGroupsProxies:
    proxies1: &proxies1 [â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, ğŸ”¯ æ•…éšœè½¬ç§», ğŸ”® è´Ÿè½½å‡è¡¡, ğŸ”— é“¾å¼ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, DIRECT, REJECT, Debug]
    proxies2: &proxies2 [ğŸš€ ä»£ç†æœåŠ¡, â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹]
    proxies3: &proxies3 [ğŸ¥ å¥ˆé£èŠ‚ç‚¹, ğŸš€ ä»£ç†æœåŠ¡, â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, Debug]
    proxies4: &proxies4 [ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸš€ ä»£ç†æœåŠ¡, â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹]
    proxies5: &proxies5 [DIRECT, Debug, ğŸš€ ä»£ç†æœåŠ¡, â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹]

proxies:
  - { name: Debug, type: socks5, server: 127.0.0.1, port: 1080, udp: true } # å ä½
  - { name: ğŸ¶ è§£é”ç½‘æ˜“äº‘ç°è‰²æ­Œæ›²(æœ¬åœ°), type: http, server: 127.0.0.1, port: 8080 } # unblockneteasemusic server

proxy-providers:
    {
      # æ‰€æœ‰èŠ‚ç‚¹
      cfw: { <<: *proxyProviders, path: ./providers/proxy/cfw.yaml },

      # é¦™æ¸¯èŠ‚ç‚¹
      hk: { <<: *proxyProviders, path: ./providers/proxy/hk.yaml, filter: 'â˜…|æ¸¯|HK|HongKong|HKT|HKBN|HGC|WTT|CMI' },

      # æ—¥æœ¬èŠ‚ç‚¹
      jp: { <<: *proxyProviders, path: ./providers/proxy/jp.yaml, filter: 'â˜…|æ—¥|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan' },

      # ç¾å›½èŠ‚ç‚¹
      us: { <<: *proxyProviders, path: ./providers/proxy/us.yaml, filter: 'â˜…|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States' },

      # å°æ¹¾èŠ‚ç‚¹
      tw: { <<: *proxyProviders, path: ./providers/proxy/tw.yaml, filter: 'â˜…|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan' },

      # ç‹®åŸèŠ‚ç‚¹
      sg: { <<: *proxyProviders, path: ./providers/proxy/sg.yaml, filter: 'â˜…|å¡|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore' },

      # éŸ©å›½èŠ‚ç‚¹
      kr: { <<: *proxyProviders, path: ./providers/proxy/kr.yaml, filter: 'â˜…|éŸ©|KR|Korea|KOR|é¦–å°”|éŸ“' },

      # å¥ˆé£èŠ‚ç‚¹
      nf: { <<: *proxyProviders, path: ./providers/proxy/nf.yaml, filter: 'â˜…|å¥ˆé£|NF|è§£é”|Netflix|NETFLIX|Media' }
    }

proxy-groups:
  - {
      name: ğŸš€ ä»£ç†æœåŠ¡, type: select, proxies: *proxies1,
      use: [cfw]
    }

  - {
      name: â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [cfw]
    }

  - {
      name: ğŸ”¯ æ•…éšœè½¬ç§», type: fallback, proxies: [Debug], lazy: true, <<: *delayInterval,
      use: [cfw]
    }

  - {
      name: ğŸ”® è´Ÿè½½å‡è¡¡, type: load-balance, proxies: [Debug], lazy: true, <<: *delayInterval, strategy: consistent-hashing,
      use: [cfw]
    }

  - {
      name: ğŸ”— é“¾å¼ä»£ç†, type: relay, proxies: [Debug, DIRECT]
    }

  - {
      name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, type: select, proxies: *proxies2
    }

  - {
      name: ğŸ“¹ æ²¹ç®¡è§†é¢‘, type: select, proxies: *proxies2
    }

  - {
      name: ğŸ¥ å¥ˆé£è§†é¢‘, type: select, proxies: *proxies3
    }

  - {
      name: âœ³ï¸ å·´å“ˆå§†ç‰¹, type: select, proxies: *proxies4
    }

  - {
      name: ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: *proxies2
    }

  - {
      name: ğŸŒ å›½å†…åª’ä½“, type: select, proxies: *proxies5
    }

  - {
      name: ğŸ“º å“”å“©å“”å“©, type: select, proxies: *proxies5
    }

  - {
      name: âš¡ï¸ æµ‹é€Ÿå¹³å°, type: select, proxies: *proxies5
    }

  - {
      name: â“‚ï¸ å¾®è½¯æœåŠ¡, type: select, proxies: *proxies5
    }

  - {
      name: ğŸ è‹¹æœæœåŠ¡, type: select, proxies: *proxies5
    }

  - {
      name: ğŸ“¢ è°·æ­ŒFCM, type: select, proxies: *proxies5
    }

  - {
      name: ğŸ® æ¸¸æˆå¹³å°, type: select, proxies: *proxies5
    }

  - {
      name: ğŸ¶ ç½‘æ˜“éŸ³ä¹, type: select, proxies: [DIRECT, Debug, ğŸ¶ è§£é”ç½‘æ˜“äº‘ç°è‰²æ­Œæ›²(æœ¬åœ°), ğŸš€ ä»£ç†æœåŠ¡]
    }

  - {
      name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT, Debug, ğŸš€ ä»£ç†æœåŠ¡, â™»ï¸ è‡ªåŠ¨åˆ‡æ¢]
    }

  - {
      name: ğŸ† å…¨çƒæ‹¦æˆª, type: select, proxies: [REJECT, DIRECT]
    }

  - {
      name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ ä»£ç†æœåŠ¡, â™»ï¸ è‡ªåŠ¨åˆ‡æ¢, DIRECT, Debug]
    }

  - {
      name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [hk]
    }

  - {
      name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [jp]
    }

  - {
      name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [us]
    }

  - {
      name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [tw]
    }

  - {
      name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [sg]
    }

  - {
      name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [kr]
    }

  - {
      name: ğŸ¥ å¥ˆé£èŠ‚ç‚¹, type: url-test, proxies: [Debug], lazy: true, <<: *delayInterval, tolerance: *urlTestTolerance,
      use: [nf]
    }

rule-providers:
    # å±€åŸŸç½‘ç›´è¿åˆ—è¡¨
    # Staert
    Lan:
        type: http
        behavior: classical
        path: ./providers/rule/Lan.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
        interval: *providersHTTPInterval

    ProcessNameDirectlist:
        type: http
        behavior: classical
        path: ./providers/rule/ProcessNameDirectlist.yaml
        url: https://raw.fgit.cf/Leyoud/Rules/master/ProcessNameDirectlist.yaml
        interval: *providersHTTPInterval
    # End

    # å…¨çƒæ‹¦æˆªåˆ—è¡¨
    # Start
    Advertising:
        type: http
        behavior: classical
        path: ./providers/rule/Advertising.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
        interval: *providersHTTPInterval

    AdvertisingAppend:
        type: http
        behavior: classical
        path: ./providers/rule/AdvertisingAppend.yaml
        url: https://raw.fgit.cf/Leyoud/Rules/master/AdvertisingAppend.yaml
        interval: *providersHTTPInterval
    # End

    # å…¨çƒç›´è¿åˆ—è¡¨(ä¸€)
    # Start
    ChinaDirectlist:
        type: http
        behavior: classical
        path: ./providers/rule/ChinaDirectlist.yaml
        url: https://raw.fgit.cf/Leyoud/Rules/master/ChinaDirectlist.yaml
        interval: *providersHTTPInterval

    GoogleCN:
        type: http
        behavior: classical
        path: ./providers/rule/GoogleCN.yaml
        url: https://raw.fgit.cf/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml
        interval: *providersHTTPInterval

    SteamCN:
        type: http
        behavior: classical
        path: ./providers/rule/SteamCN.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
        interval: *providersHTTPInterval
    # End

    # ç”µæŠ¥æ¶ˆæ¯
    Telegram:
        type: http
        behavior: classical
        path: ./providers/rule/Telegram.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
        interval: *providersHTTPInterval

    # æ²¹ç®¡è§†é¢‘
    YouTube:
        type: http
        behavior: classical
        path: ./providers/rule/YouTube.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
        interval: *providersHTTPInterval

    # å¥ˆé£è§†é¢‘
    Netflix:
        type: http
        behavior: classical
        path: ./providers/rule/Netflix.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical.yaml
        interval: *providersHTTPInterval

    # å·´å“ˆå§†ç‰¹
    Bahamut:
        type: http
        behavior: classical
        path: ./providers/rule/Bahamut.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml
        interval: *providersHTTPInterval

    # å›½å¤–åª’ä½“
    GlobalMedia:
        type: http
        behavior: classical
        path: ./providers/rule/GlobalMedia.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
        interval: *providersHTTPInterval

    # å“”å“©å“”å“©
    BilibiliHMT:
        type: http
        behavior: classical
        path: ./providers/rule/BilibiliHMT.yaml
        url: https://raw.fgit.cf/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BilibiliHMT.yaml
        interval: *providersHTTPInterval

    # å›½å†…åª’ä½“
    ChinaMedia:
        type: http
        behavior: classical
        path: ./providers/rule/ChinaMedia.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
        interval: *providersHTTPInterval

    # æµ‹é€Ÿå¹³å°
    Speedtest:
        type: http
        behavior: classical
        path: ./providers/rule/Speedtest.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
        interval: *providersHTTPInterval

    # å¾®è½¯æœåŠ¡
    Microsoft:
        type: http
        behavior: classical
        path: ./providers/rule/Microsoft.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
        interval: *providersHTTPInterval

    # è‹¹æœæœåŠ¡
    Apple:
        type: http
        behavior: classical
        path: ./providers/rule/Apple.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical.yaml
        interval: *providersHTTPInterval

    # è°·æ­ŒFCM
    GoogleFCM:
        type: http
        behavior: classical
        path: ./providers/rule/GoogleFCM.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
        interval: *providersHTTPInterval

    # æ¸¸æˆå¹³å°
    # Start
    Epic:
        type: http
        behavior: classical
        path: ./providers/rule/Epic.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml
        interval: *providersHTTPInterval

    Sony:
        type: http
        behavior: classical
        path: ./providers/rule/Sony.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.yaml
        interval: *providersHTTPInterval

    Steam:
        type: http
        behavior: classical
        path: ./providers/rule/Steam.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
        interval: *providersHTTPInterval

    Origin:
        type: http
        behavior: classical
        path: ./providers/rule/Origin.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.yaml
        interval: *providersHTTPInterval

    Nintendo:
        type: http
        behavior: classical
        path: ./providers/rule/Nintendo.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.yaml
        interval: *providersHTTPInterval
    # End

    # ç½‘æ˜“éŸ³ä¹
    NeteaseMusic:
        type: http
        behavior: classical
        path: ./providers/rule/NetEaseMusic.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml
        interval: *providersHTTPInterval

    # ä»£ç†æœåŠ¡åˆ—è¡¨
    # Start
    GlobalProxylist:
        type: http
        behavior: classical
        path: ./providers/rule/GlobalProxylist.yaml
        url: https://raw.fgit.cf/Leyoud/Rules/master/GlobalProxylist.yaml
        interval: *providersHTTPInterval

    Global:
        type: http
        behavior: classical
        path: ./providers/rule/Global.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml
        interval: *providersHTTPInterval
    # End

    # å…¨çƒç›´è¿åˆ—è¡¨(äºŒ)
    # Start
    China:
        type: http
        behavior: classical
        path: ./providers/rule/China.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml
        interval: *providersHTTPInterval

    ChinaIPs:
        type: http
        behavior: classical
        path: ./providers/rule/ChinaIPs.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_Classical.yaml
        interval: *providersHTTPInterval

    Download:
        type: http
        behavior: classical
        path: ./providers/rule/Download.yaml
        url: https://raw.fgit.cf/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml
        interval: *providersHTTPInterval
    # End

rules:
  - RULE-SET,Lan,DIRECT
  - RULE-SET,ProcessNameDirectlist,DIRECT
  - RULE-SET,Advertising,ğŸ† å…¨çƒæ‹¦æˆª
  - RULE-SET,AdvertisingAppend,ğŸ† å…¨çƒæ‹¦æˆª
  - RULE-SET,ChinaDirectlist,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,YouTube,ğŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,Netflix,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,Bahamut,âœ³ï¸ å·´å“ˆå§†ç‰¹
  - RULE-SET,GlobalMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,BilibiliHMT,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,Speedtest,âš¡ï¸ æµ‹é€Ÿå¹³å°
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,Epic,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Sony,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Steam,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Origin,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo,ğŸ® æ¸¸æˆå¹³å°
  - PROCESS-NAME,cloudmusic.exe,ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,NeteaseMusic,ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,GlobalProxylist,ğŸš€ ä»£ç†æœåŠ¡
  - RULE-SET,Global,ğŸš€ ä»£ç†æœåŠ¡
  - RULE-SET,China,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaIPs,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
